version : '2'

services :
  backend : 
      restart : always
      build : ./backend
      expose : 
          - "8000"
      command : /usr/local/bin/gunicorn -w 2 -b :8000 project:app
      depends_on :
          - postgres

  nginx : 
      restart : always
      build : ./nginx
      ports : 
          - "80:80"
      volumes_from :
          - backend
      depends_on :
          - backend
  
  data : 
      image : postgres:latest
      volumes : 
          - /var/lib/postgresql
      command : "true"
      
  postgres : 
      restart : always
      build : ./postgresql
      volumes_from : 
            - data
      ports : 
          - "5432:5432"