"""minor changes

Revision ID: 160de66dbc2a
Revises: 2b3baae302aa
Create Date: 2018-05-19 03:02:50.184121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160de66dbc2a'
down_revision = '2b3baae302aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fyle_tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('fyle_tokens', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fyle_tokens', 'updated_at')
    op.drop_column('fyle_tokens', 'created_at')
    # ### end Alembic commands ###
