"""added changes

Revision ID: 1e73769f19af
Revises: 5a524deee1e3
Create Date: 2018-05-17 12:13:35.690777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e73769f19af'
down_revision = '5a524deee1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('expense_details', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('expenses_expense_id_key', 'expenses', type_='unique')
    op.drop_column('expenses', 'expense_id')
    op.drop_column('expenses', 'amount')
    op.drop_column('expenses', 'details')
    op.drop_column('expenses', 'source')
    op.drop_column('expenses', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('expense_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('expenses_expense_id_key', 'expenses', ['expense_id'])
    op.drop_column('expenses', 'expense_details')
    # ### end Alembic commands ###
