"""added access_token fieldd

Revision ID: 263ff6feb265
Revises: e2ffb6b8809f
Create Date: 2018-05-24 15:47:57.611093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263ff6feb265'
down_revision = 'e2ffb6b8809f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fyle_tokens', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fyle_tokens', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
