"""updated model

Revision ID: 2b3baae302aa
Revises: 1e73769f19af
Create Date: 2018-05-18 15:03:45.051523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3baae302aa'
down_revision = '1e73769f19af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fyle_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('refresh_token', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('ext_expense_id', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('expenses', 'updated_at')
    op.drop_column('expenses', 'ext_expense_id')
    op.drop_column('expenses', 'created_at')
    op.drop_table('fyle_tokens')
    # ### end Alembic commands ###
