"""change in n fyletoken

Revision ID: a5faba572043
Revises: 15f340a056be
Create Date: 2018-05-31 15:23:28.968796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5faba572043'
down_revision = '15f340a056be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fyle_tokens', sa.Column('username', sa.String(), nullable=False))
    op.create_foreign_key(None, 'fyle_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fyle_tokens', type_='foreignkey')
    op.drop_column('fyle_tokens', 'username')
    # ### end Alembic commands ###
