"""adchnaged to json

Revision ID: c9d4a33ab230
Revises: 263ff6feb265
Create Date: 2018-05-24 16:19:05.579691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9d4a33ab230'
down_revision = '263ff6feb265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fyle_tokens', sa.Column('tokens', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('fyle_tokens', 'access_token')
    op.drop_column('fyle_tokens', 'refresh_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fyle_tokens', sa.Column('refresh_token', sa.VARCHAR(length=48), autoincrement=False, nullable=True))
    op.add_column('fyle_tokens', sa.Column('access_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('fyle_tokens', 'tokens')
    # ### end Alembic commands ###
